<a href="https://colab.research.google.com/github/GopiMindgloer/Machine_Learning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [0]:
type(a)

numpy.ndarray

In [0]:
a.dtype.name

'int64'

In [0]:
a.data

In [0]:
a.itemsize

8

In [0]:
b = np.array(((1,2,3),(4,5,6)))

In [0]:
type(b)

numpy.ndarray

In [0]:
b.dtype

dtype('int64')

In [0]:
c = np.array([[1,2,3],[4,3,5]],dtype='complex')

In [0]:
c = np.ones((3,3))
sum(c)

array([3., 3., 3.])

In [0]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0,8,3)

array([0, 3, 6])

In [0]:
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [0]:
a = np.random.random(3)

In [0]:
a*10

array([1.66145917, 7.43481227, 7.21686892])

In [0]:
a = np.arange(0,27).reshape(3,3,3)

In [0]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [0]:
sum(a)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [0]:
a.sum()

351

In [0]:
x = np.arange(10,19).reshape(3,3)
x

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [0]:
x[1:2,1:2]

array([[4]])

In [0]:
for i in x:
  print(x)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [0]:
for row in x:
  print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [0]:
x[[0,1,2],0:2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [0]:
x = np.arange(0,9)
print(x)
x[1:3]

[0 1 2 3 4 5 6 7 8]


array([1, 2])

In [0]:
for i in x:
  print(i)

0
1
2
3
4
5
6
7
8


In [0]:
x>5

array([False, False, False, False, False, False,  True,  True,  True])

In [0]:
x.shape = (3,3)

In [0]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
x.shape = (9)

In [0]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
A = np.random.random(9).reshape(3,3)

In [0]:
A

array([[0.1065688 , 0.13527216, 0.50604444],
       [0.2748907 , 0.50417899, 0.57641347],
       [0.7725273 , 0.42517864, 0.30509818]])

In [0]:
A = np.ones((3,3))